### PR TITLE
Container

### PR DESCRIPTION
**Pull request by stswidwinski**
Changes:

1. Changed the layout of the make file. 
  - All of our header files must be in include/batch. 
  - All of our source files must be in src/batch. HOWEVER, any templated class must have .cc file within include and include it within the header. 
  - All of our test fixtures must be in include/test
  - All of our tests must be in test/ NOTE: the test main function is in test/sample_test.cc. We should likely rename this soon, but w/e for now ^^

2. Added the interface for any container. include/batch/container.h
3. Added the simple array implementation. include/batch/arr_container.h
4. Added test fixtures for txn and action (include/test/test_txn.h and include/test/test_action.h)

### CODE REVIEW

**Comment by stswidwinski** [comment]
Rebased onto new master.

**Comment by stswidwinski** [comment]
Note:

I template for Action and require action to have an overloaded < operator. That should help you in implementing actions Matt!

**Comment by stswidwinski** [comment]
Rebased onto the interface PR

**Comment by matthewbrady** [comment]
> I template for Action and require action to have an overloaded < operator. That should help you in implementing actions Matt!

The idea here is that we want to be able to sort actions by some metric (number of lock requests for example), right?

**Comment by stswidwinski** [comment]
No, there is no template any more -- look through the code please! I have an explicit interface defined for two reasons:

1. We may want any weird shit on top of what we need for benchmarking and timing the system
2. I need the interface to define the scheduling classes

Does that make sense?

**Comment by matthewbrady** [comment]
Ok but the purpose of this requirement
` +    virtual bool operator<(const BatchAction& ba2) const = 0; `
is to allow sorting of actions? I agree that the interface is better than the template, but just wanted to confirm this the intended use of the comparison operator (looking at test_action.h I'm pretty sure it is).

**Comment by matthewbrady** [comment]
Noticed a couple swap files you probably didn't mean to 
include.include/test/.test_action.h.swp
include/batch/.batch_action.h.swp
test/.arr_container_test.cc.swp

Otherwise seems good to me.

**Comment by stswidwinski** [comment]
Yeah, that's it! :) To be more specific:

The packing logic must have a way of ordering actions. I assume we may just use the overloaded "<" so that there is a very simple way of providing many different ways of ordering with very little hustle

**Comment by stswidwinski** [comment]
Yeah, sorry for the swaps :( I'll get rid of them after im done with lock stages

**Pull request merged**
